### ISSUE TITLE
是否可以只对u开头的数据做清洗？

### ISSUE THREAD

**Issue by lyw615** [zwl-max/underwater-detection#1]
发布的比赛数据里说过c开头的数据基本没问题，u开头的数据基本会有噪声在里面。如果只对u开头的数据做清洗，是否也能达到同样的训练效果呢？

**Comment by zwl-max** [comment]
1. c开头也有几张不干净的数据，所以我是对c和u开头的数据一起做清洗的。
2. 只对u开头的数据做清洗，是否也能达到同样的训练效果呢？
这个没做实验，不知道是否可以。
