### ISSUE TITLE
a question about data clean

### ISSUE THREAD

**Issue by Yangr116** [zwl-max/underwater-detection#3]
您好，想问一下数据清洗是用那种方式训练和测试呢？
1. 所有数据训练，所有数据测试
2. 划分train和val,每次对val进行清洗

**Comment by zwl-max** [comment]
第一种方式
On 1/17/2022 ***@***.***> wrote：

您好，想问一下数据清洗是用那种方式训练和测试呢？

所有数据训练，所有数据测试
划分train和val,每次对val进行清洗

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Yangr116** [comment]
感谢



---Original---
From: ***@***.***&gt;
Date: Mon, Jan 17, 2022 17:52 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [zwl-max/underwater-detection] a question about data clean (Issue #3)




 第一种方式
 On 1/17/2022 ***@***.***&gt; wrote：
 
 您好，想问一下数据清洗是用那种方式训练和测试呢？
 
 所有数据训练，所有数据测试
 划分train和val,每次对val进行清洗
 
 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android.
 You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
