### ISSUE TITLE
Is it possible to share the dataset, thanks a lot?

### ISSUE THREAD

**Issue by junyongyou** [zwl-max/underwater-detection#4]
Hi, I know the contest has already finished and the organizer has closed the dataset. I am just wondering if it is possible that you still have the dataset and can share with me? I am working on a similar project. Thank you so much.

**Comment by zwl-max** [comment]
链接:https://pan.baidu.com/s/1YN9czMdhde6AfYwoMacLUQ 提取码:safw 复制这段内容后打开百度网盘手机App，操作更方便哦



On 4/24/2022 21:53，Junyong ***@***.***> wrote：

Hi, I know the contest has already finished and the organizer has closed the dataset. I am just wondering if it is possible that you still have the dataset and can share with me? I am working on a similar project. Thank you so much.

**Comment by junyongyou** [comment]
Great, thanks a lot.
